### PR TITLE
More minor fixes.

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
How good is the testing in this repo? I'm pretty confident this doesn't break anything but if it did, would the tests catch it?

**Comment by apelisse** [comment]
There is not a lot of confidence, but it's getting better. I suspect the integration test should catch the functionality of this change.

You are technically changing the API of the generator package (removing `NewOpenAPIGen`), so we'd need to find all the consumer of this package?

**Comment by lavalamp** [comment]
I did search k/k and no one appeared to be calling the function.

**Comment by lavalamp** [comment]
oh whoops, I thought this merged and accidentally reused the branch. one sec.

**Comment by lavalamp** [comment]
This should be mergable again. @seans or @mbohlool could one of you approve?

**Comment by roycaihw** [comment]
Closing as the change has been included in #111 

/close

**Pull request closed without merging**
