### PR TITLE
I created an empty commit, not sure how 🤷🏻

### PR DESCRIPTION
**Pull request by apelisse-tester**

### CODE REVIEW

**Comment by apelisse-tester** [comment]
Argh, I need to sign the CLA ...

**Comment by apelisse-tester** [comment]
I used the email of a friend to get a free CLA check!

**Comment by apelisse-tester** [comment]
cc @liggitt

**Comment by apelisse** [comment]
Amazing piece of code, Kelsey would be proud of you, definitely doesn't need to be tested!
/lgtm
/approve

**Comment by apelisse** [comment]
I don't know if you should approve Jordan, I have a feeling it would get merged to be honest ... (the bot basically only says it's missing the approved label).

**Comment by liggitt** [comment]
I'm not an approver on this repo. Looks like the approve bot doesn't understand empty commits

**Comment by apelisse** [comment]
yeah, it sounds like we have two separate bugs :-) The empty commit one is really not that bad since that basically never happens, the one where we can merge untested code is more problematic.

**Comment by apelisse** [comment]
I've marked the CI jobs as required, but I suspect the config will be reset by some bot. @liggitt do you remember where the configs are committed?

**Comment by liggitt** [comment]
> @liggitt do you remember where the configs are committed?

I'm not sure... I didn't remember repo CI config being synced that way, but I might have just missed it

**Comment by apelisse** [comment]
Opened an issue in: https://github.com/kubernetes/test-infra/pull/26588

**Comment by BenTheElder** [comment]
>  Looks like the approve bot doesn't understand empty commits

Yeah, it's a known issue that for some reason handling was previously rejected, I've dug up about as much context as I can find quickly, and a bonus fun approval quirk :-)
https://github.com/kubernetes/test-infra/pull/7675
https://github.com/kubernetes/test-infra/issues/9238
https://github.com/kubernetes/kubernetes/pull/92316

**Comment by apelisse** [comment]
OK So it looks like the name of the checks have changed since we merged the PR, what a joke ... Not sure what I'm supposed to call it now.

**Comment by apelisse** [comment]
OK it looks like they are required now? Not sure if someone changed something :-)

**Comment by apelisse** [comment]
This works by the way, great!
/close

**Pull request closed without merging**
