### PR TITLE
Go 1.18

### PR DESCRIPTION
**Pull request by apelisse**
That should help with #302.

### CODE REVIEW

**Comment by apelisse** [comment]
Oops, I actually took #302 with me.

**Comment by apelisse** [comment]
I'll remove it once the CI/CD fails/succeeds.

**Comment by apelisse** [comment]
And I've changed the CI so we need to update test-infra/config/prow/config.yaml again.

**Comment by apelisse** [comment]
OK That should be good to go now, thanks @liggitt

**Comment by apelisse** [comment]
(if we apply this on top of 302, it does indeed clean up dependencies significantly).

**Review by chendave — COMMENTED** [review]
LGTM, verified on my side, the Ginkgo v1 dep will be removed after applying this pr on top of https://github.com/kubernetes/kube-openapi/pull/302

**Comment by apelisse** [comment]
Thanks!

**Comment by apelisse** [comment]
I'm force-merging this one since the required CI can't pass ...

**Pull request merged**
