### PR TITLE
Collect params for OpenAPI V3

### PR DESCRIPTION
**Pull request by Jefftree**
```
goos: darwin
goarch: arm64
pkg: k8s.io/kube-openapi/pkg/spec3
BenchmarkSharedParamsDeserialize/apiv1spec.json-8         	      98	  12138503 ns/op	12245326 B/op	   60819 allocs/op
BenchmarkSharedParamsDeserialize/apiv1spec.sharedparams.json-8         	     100	  10520641 ns/op	 9892803 B/op	   68528 allocs/op
BenchmarkSharedParamsDeserialize/appsv1spec.json-8                     	     200	   5920978 ns/op	 5708092 B/op	   27386 allocs/op
BenchmarkSharedParamsDeserialize/appsv1spec.sharedparams.json-8        	     230	   5162531 ns/op	 4871387 B/op	   30219 allocs/op
BenchmarkSharedParamsDeserialize/authorizationv1spec.json-8            	    2575	    466165 ns/op	  537114 B/op	    2521 allocs/op
BenchmarkSharedParamsDeserialize/authorizationv1spec.sharedparams.json-8         	    2620	    458194 ns/op	  526593 B/op	    2664 allocs/op
PASS
ok  	k8s.io/kube-openapi/pkg/spec3	9.266s
```

k/k diff PR: https://github.com/kubernetes/kubernetes/pull/120242

### CODE REVIEW

**Comment by apelisse** [comment]
Can we get a quick performance impact of this?

**Comment by Jefftree** [comment]
https://github.com/kubernetes/kubernetes/pull/120242/commits/afa3e4574edd78b437c3a76637153d1bcb1531a3 shows the OpenAPI diff.

For sizes: 
/api/v1 showed some nice improvement from 1.7MB -> 1MB
The other endpoints had some reduction between 10-20%

I will gather some additional numbers on cpu/mem differences if any exist.

This PR is still WIP, so feel free to hold off on review.

**Comment by apelisse** [comment]
Yeah, I think what you could do is use these new OpenAPI and re-run some of the benchmarks we have to see CPU/Memory allocation reductions.

**Comment by Jefftree** [comment]
/cc @sttts 
This was pretty much a copy and paste of the v2 param collector with one change.
- The fieldValidation and dryRun unsharing special condition was removed. The two parameters are used until v1.26 and v1.27 respectively and this change will go into 1.29 which should be outside the 1 version skew that kubectl supports?

**Comment by apelisse** [comment]
Do you know why allocs are going up?

**Comment by Jefftree** [comment]
@apelisse @sttts This PR will need to be rebased, but is this change something we're okay with landing?

**Comment by drewmullen** [comment]
Any idea what happened with this PR? We are missing several k8s primitives and I believe this may be the fix we need: https://github.com/harvester/harvester/issues/5500

**Pull request closed without merging**
