### PR TITLE
Correction in README.md

### LINKED ISSUE #95: Integration test README corrections
Found following issues in the README inside test/integration folder

1) The command to generate openapi_generated.go should be:

go run ../../cmd/openapi-gen/openapi-gen.go -i "./testdata/listtype" -o pkg -p generated -O openapi_generated

2) There is a typo in this line: The generated file `pkg/generaged/openapi_generated.go` should have been created.

It should be "pkg/generated/openapi_generated.go"

### PR DESCRIPTION
**Pull request by RA489**
Correction in README.md 
fixes #95

### CODE REVIEW

**Comment by yujuhong** [comment]
I don't know much about open api. 

/cc @mbohlool  @kubernetes/sig-api-machinery-pr-reviews

**Comment by mbohlool** [comment]
Looks fine to me but giving @seans3 a chance to review this. He developed integration test in kube-openapi.

**Pull request merged**
