### PR TITLE
Add a go.mod for integration test

### PR DESCRIPTION
**Pull request by dims**
To prevent leaking test only dependencies into the root go.mod file

gets rid of 3 things from go.mod/sum

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
see graph below on how we end up with `getkin/kin-openapi` in kubernetes/kubernetes

image

**Comment by lavalamp** [comment]
Nice change!

/lgtm
/approve

**Comment by apelisse** [comment]
Nice, thanks!

**Pull request merged**
