### PR TITLE
Bump github.com/emicklei/go-restful/v3 to v3.10.1

### PR DESCRIPTION
**Pull request by lucacome**
Bumps github.com/emicklei/go-restful/v3 from `v3.8.0` to `v3.10.1`

### CODE REVIEW

**Comment by lucacome** [comment]
@Jefftree @yujuhong anything I need to do to get this merged?

**Comment by Jefftree** [comment]
Is there anything from the newer version that we specifically need?

**Comment by lucacome** [comment]
@Jefftree some scanners are still showing `v3.8.0` as vulnerable. I couldn't find any evidence of it myself but I thought it wouldn't hurt to update.

**Comment by Jefftree** [comment]
To keep things consistent with kubernetes/kubernetes, can we go to 3.9? https://github.com/kubernetes/kubernetes/blob/master/go.mod#L33

**Comment by lucacome** [comment]
Just opened https://github.com/kubernetes/kubernetes/pull/115067 🙂

**Pull request closed without merging**
