### PR TITLE
Drop ghodss/yaml and switch to sigs.k8s.io/yaml

### PR DESCRIPTION
**Pull request by dims**
Cleaning up the yaml dependency!

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by apelisse** [comment]
Seems mechanical to me :-)
/lgtm

**Comment by apelisse** [comment]
How come there's not test running on this pull-request/repo?

**Comment by apelisse** [comment]
@dims Have you been able to run the tests? It looks like we don't have any automated thing anymore. Time to lgtm/approve that workflow change :-)

**Comment by dims** [comment]
@apelisse done!

```ok  	k8s.io/kube-openapi/pkg/util/proto/validation	0.363s```

**Comment by apelisse** [comment]
Thanks :-)
/approve

**Pull request merged**
