### PR TITLE
Switch location for goautoneg vendored code

### PR DESCRIPTION
**Pull request by dims**
Move to github.com/munnerz/goautoneg as bitbucket is flaky!

Change-Id: I1c63240a4985b9e4ae33d23af929657d44f356a0

### CODE REVIEW

**Comment by dims** [comment]
@mbohlool @lavalamp @seans3 ping!

**Comment by roycaihw** [comment]
This has some overlap with https://github.com/kubernetes/kube-openapi/pull/128 (bitbucket recently dropped support for TLS 1.0 and 1.1). Would like to see us to use TLS 1.2 anyway. 

According to conversation in https://github.com/kubernetes/test-infra/issues/10461, switching to a fork seems to be desired from sig-testing. 

/lgtm

Need someone else to approve.

**Pull request merged**
