### PR TITLE
Update googleapis/gnostic

### LINKED ISSUE #167: "gnostic" should be updated
Hi

With the current version of `gnostic` we got the following message. 

```
/private/var/tmp/_bazel_a13705/d47ee6d5190331e265fc3deb51db2812/external/bazel_gazelle/internal/go_repository.bzl:184:13: gazelle: gazelle: finding module path for import github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/apis_guru/apis_guru: exit status 1: go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/apis_guru/apis_guru latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/apis_guru latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator latest
go: finding github.com/googleapis/gnostic/plugins latest
can't load package: package github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/apis_guru/apis_guru: unknown import path "github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/apis_guru/apis_guru": cannot find module providing package github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/apis_guru/apis_guru
gazelle: finding module path for import github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore: exit status 1: go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator latest
go: finding github.com/googleapis/gnostic/plugins latest
can't load package: package github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore: unknown import path "github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore": cannot find module providing package github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore
gazelle: finding module path for import github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore: exit status 1: go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples latest
go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator latest
go: finding github.com/googleapis/gnostic/plugins latest
can't load package: package github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore: unknown import path "github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore": cannot find module providing package github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore
gazelle: finding module path for import github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/xkcd/xkcd: exit status 1: go: finding github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples/v2.0/xkcd/xkcd latest
```

Related issue: https://github.com/kubernetes/client-go/issues/636

### PR DESCRIPTION
**Pull request by nghialv**
Resolve #167

### CODE REVIEW

**Comment by nghialv** [comment]
@k8s-ci-robot singed

**Comment by sttts** [comment]
@nghialv thanks for the PR!

**Comment by nghialv** [comment]
@sttts Thank you.
I have just created a PR to Kubernetes to update `apimachinery` too.
https://github.com/kubernetes/kubernetes/pull/80293

**Pull request merged**
