### PR TITLE
fix for hardcoded path needed to pass tests in github-ci

### LINKED ISSUE #225: hardcoded `git checkout` path at $GOPATH/src/k8s.io, is required, to pass `go test`, using github-actions
Hi,

In github-actions ci, _"go test"_ fails, unless a _"mkdir $GOPATH/src/k8s.io"_ is done  _"$GOPATH/src"_ and _"git clone"_ is executed under _$GOPATH/src/k8s.io"_  .

But _"go build"_ works without the above specific path. So I am assuming that some piece of code under $PROJECT_HOME/test needs looking into.

Details here https://github.com/kubernetes/kube-openapi/pull/226

### PR DESCRIPTION
**Pull request by longwuyuan**
https://github.com/kubernetes/kube-openapi/issues/225

### CODE REVIEW

**Comment by palnabarun** [comment]
@longwuyuan -- can you please rewrite your commit message according to the conventions laid down in https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines ?

Same for the PR title.

**Comment by longwuyuan** [comment]
> @longwuyuan -- can you please rewrite your commit message according to the conventions laid down in https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines ?
> 
> Same for the PR title.

Oh sorry. I assumed that the elaborate text in 225 will be duplicated here.
Changing the commit message and the PR title now

**Comment by apelisse** [comment]
That looks great, thanks!
/lgtm

**Comment by apelisse** [comment]
cc @liggitt

**Pull request merged**
