### PR TITLE
Move to newer version (v3) of github.com/emicklei/go-restful

### PR DESCRIPTION
**Pull request by dims**
Related to: https://github.com/kubernetes/kubernetes/issues/110338

Intended to pick up change in https://github.com/emicklei/go-restful/commit/f292efff46ae17e9d104f865a60a39a2ae9402f1

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
tested this in https://github.com/kubernetes/kubernetes/pull/110351 to ensure all the presubmit jobs in k/k are green.

**Comment by sttts** [comment]
Lgtm. Would like to see a proof PR in kube, just to be sure. Looks (too) innocent here.

**Comment by sttts** [comment]
Ack, missed https://github.com/kubernetes/kubernetes/pull/110351.

**Pull request merged**
