### PR TITLE
Fix api linter

### PR DESCRIPTION
**Pull request by lavalamp**
Includes #109.

### CODE REVIEW

**Comment by lavalamp** [comment]
I've only run the unit tests.

**Comment by lavalamp** [comment]
I'm fighting a bit with the integration test.

Ordinary usage should not need to do anything fancy, just call with the --verify flag rather than checking with the diff command. The integration test here does indeed need to do something different :/

**Comment by lavalamp** [comment]
OK, with this change it prepends the output package to the report file name. I'll fix it later.

**Comment by lavalamp** [comment]
OK, I've now fixed the integration test. PTAL.

**Comment by roycaihw** [comment]
LGTM.

One nit is that the `test/integration/pkg/generated/openapi_generated.go` change doesn't need to be checked-in (was trying to update the [README](https://github.com/kubernetes/kube-openapi/pull/107/files#diff-e1d8df67760b2710208b2dd3263cf74a)).

**Pull request merged**
