### PR TITLE
implements Schemas, SecuritySchemes and Paths of OASv3 spec

### PR DESCRIPTION
**Pull request by p0lyn0mial**
these fields can be found at:
1. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
2. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securitySchemeObject
3. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathsObject

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
referencing https://github.com/p0lyn0mial/spec3/pull/1 as it already has some comments.

**Comment by yue9944882** [comment]
> pkg/spec3/component_test.go:9:2: unknown import path "github.com/p0lyn0mial/spec3": cannot find module providing package 

thank you for starting this! it doesn't seem to compile for now tho

**Comment by p0lyn0mial** [comment]
> it doesn't seem to compile for now tho

fixed.

**Comment by yue9944882** [comment]
are we reviving the thread?

**Comment by sttts** [comment]
> are we reviving the thread?

yeah!

**Pull request closed without merging**
