### PR TITLE
Missed a spot for klog flag initialization

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I43e37728b7558702a41ceaa7e9f7b722aaa55bf7

### CODE REVIEW

**Comment by lavalamp** [comment]
I thought @roycaihw just deleted this, did his change not merge yet? I've approved it like a dozen times now ;) ;)

**Comment by roycaihw** [comment]
@lavalamp The openapi-gen cmd I deleted was in k/k: https://github.com/kubernetes/kubernetes/pull/66409, which was not being used.

The cmd being modified in this PR is in kube-openapi, and it is what we currently use in kubernetes makefile.

**Comment by roycaihw** [comment]
/lgtm

Let's keep in mind about entirely removing klog from kube-openapi after merging this PR.

**Comment by lavalamp** [comment]
Oh, I thought this PR was in the main repo. (It shows "... into `kubernetes:master` from ..." at the top, is it a github bug?)

/lgtm
/approve

**Comment by dims** [comment]
@lavalamp ENOCLUE :)

**Pull request merged**
