### PR TITLE
[Do not merge] Bump structured-merge-diff dependency to version 2

### PR DESCRIPTION
**Pull request by jennybuckley**
This is intended for a new branch 'release-1.17'

Making this as a PR to master to make sure it will pass the tests.

### CODE REVIEW

**Comment by jennybuckley** [comment]
The base for the branch is https://github.com/kubernetes/kube-openapi/commit/30be4d16710ac61bce31eb28a01054596fe6a9f1 which happens to be the same as master right now, but is also the version used by kubernetes 1.17 https://github.com/kubernetes/kubernetes/blob/release-1.17/go.mod#L155

**Comment by jennybuckley** [comment]
/hold
We are saving this for when (if) we need to cherry-pick something to smd in kubernetes 1.17

**Comment by apelisse** [comment]
v1.17.5-beta.0: looks like the base commit hasn't changed. creating branch.

**Comment by apelisse** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.17.5-beta.0/go.mod#L155

**Comment by apelisse** [comment]
I've just created a release-1.17 branch from that base commit, we should rebase that PR there.

**Comment by apelisse** [comment]
Replaced by #188

**Pull request closed without merging**
