### PR TITLE
Drop unused mapstructure functionality

### PR DESCRIPTION
**Pull request by liggitt**
Cleans up unused dependency

### CODE REVIEW

**Comment by apelisse** [comment]
Looks good to me, but curious if @alexzielenski uses that?

**Comment by liggitt** [comment]
I *think* this was residual from the old go-openapi repos

**Comment by alexzielenski** [comment]
> Looks good to me, but curious if @alexzielenski uses that?

nope, we are doing some things with strfmt in kubectl-validate but nothing regarding this mapstructure dep

**Comment by liggitt** [comment]
dropped WIP, ready whenever you are

**Pull request merged**
